spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sss
    password: sss
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  ssl:
    key-store: classpath:sec-rest-tls.jks
    key-store-type: pkcs12
    key-store-password: ssssss
    key-password: ssssss
    key-alias: sec-rest-tls
  port: 8443